events {
    worker_connections 1024;
}

http {
    upstream ml_api {
        # Right now, all traffic goes to the BLUE container
        server host.docker.internal:9096;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://ml_api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}